name: Cypress

on: [deployment_status]
jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Test
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - name: Run Posttest
        run: npm run posttest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}